// AUTO-GENERATED from Enka store (avatars.json). Base stats approximate (level 60).
export interface GeneratedAgent {
  id: string; name: string; element: string; role: string;
  baseAtk: number; baseCritRate: number; baseCritDmg: number;
}
export const GENERATED_AGENTS: GeneratedAgent[] = [
  { id: "1011", name: "Anbi", element: "Elec", role: "Stun", baseAtk: 584, baseCritRate: 5, baseCritDmg: 50 },
  { id: "1021", name: "Tsubaki", element: "Physics", role: "Attack", baseAtk: 836, baseCritRate: 5, baseCritDmg: 50 },
  { id: "1031", name: "Nostradamus", element: "Ether", role: "Support", baseAtk: 574, baseCritRate: 5, baseCritDmg: 50 },
  { id: "1041", name: "Longinus", element: "Fire", role: "Attack", baseAtk: 814, baseCritRate: 5, baseCritDmg: 50 },
  { id: "1051", name: "Yidhari", element: "Ice", role: "Rupture", baseAtk: 785, baseCritRate: 5, baseCritDmg: 50 },
  { id: "1061", name: "Corin", element: "Physics", role: "Attack", baseAtk: 732, baseCritRate: 5, baseCritDmg: 50 },
  { id: "1071", name: "Caesar", element: "Physics", role: "Defense", baseAtk: 637, baseCritRate: 5, baseCritDmg: 50 },
  { id: "1081", name: "Billy", element: "Physics", role: "Attack", baseAtk: 712, baseCritRate: 5, baseCritDmg: 50 },
  { id: "1091", name: "Unagi", element: "FireFrost", role: "Anomaly", baseAtk: 806, baseCritRate: 5, baseCritDmg: 50 },
  { id: "1101", name: "Ookuma Mari", element: "Fire", role: "Stun", baseAtk: 661, baseCritRate: 5, baseCritDmg: 50 },
  { id: "1111", name: "Anton", element: "Elec", role: "Attack", baseAtk: 717, baseCritRate: 5, baseCritDmg: 50 },
  { id: "1121", name: "Ben", element: "Fire", role: "Defense", baseAtk: 578, baseCritRate: 5, baseCritDmg: 50 },
  { id: "1131", name: "Aokaku", element: "Ice", role: "Support", baseAtk: 591, baseCritRate: 5, baseCritDmg: 50 },
  { id: "1141", name: "Lycaon", element: "Ice", role: "Stun", baseAtk: 654, baseCritRate: 5, baseCritDmg: 50 },
  { id: "1151", name: "Lucy", element: "Fire", role: "Support", baseAtk: 584, baseCritRate: 5, baseCritDmg: 50 },
  { id: "1161", name: "Lighter", element: "Fire", role: "Stun", baseAtk: 723, baseCritRate: 5, baseCritDmg: 50 },
  { id: "1171", name: "Burnice", element: "Fire", role: "Anomaly", baseAtk: 788, baseCritRate: 5, baseCritDmg: 50 },
  { id: "1181", name: "Lisa", element: "Elec", role: "Anomaly", baseAtk: 751, baseCritRate: 5, baseCritDmg: 50 },
  { id: "1191", name: "Ellen", element: "Ice", role: "Attack", baseAtk: 863, baseCritRate: 5, baseCritDmg: 50 },
  { id: "1201", name: "Harumasa", element: "Elec", role: "Attack", baseAtk: 841, baseCritRate: 5, baseCritDmg: 50 },
  { id: "1211", name: "Rina", element: "Elec", role: "Support", baseAtk: 642, baseCritRate: 5, baseCritDmg: 50 },
  { id: "1221", name: "Yanagi", element: "Elec", role: "Anomaly", baseAtk: 798, baseCritRate: 5, baseCritDmg: 50 },
  { id: "1241", name: "Zhu Yuan", element: "Ether", role: "Attack", baseAtk: 844, baseCritRate: 5, baseCritDmg: 50 },
  { id: "1251", name: "Qing Yi", element: "Elec", role: "Stun", baseAtk: 683, baseCritRate: 5, baseCritDmg: 50 },
  { id: "1261", name: "Jane Doe", element: "Physics", role: "Anomaly", baseAtk: 806, baseCritRate: 5, baseCritDmg: 50 },
  { id: "1271", name: "Seth", element: "Elec", role: "Defense", baseAtk: 568, baseCritRate: 5, baseCritDmg: 50 },
  { id: "1281", name: "Clara", element: "Physics", role: "Anomaly", baseAtk: 683, baseCritRate: 5, baseCritDmg: 50 },
  { id: "1291", name: "Hugo Vlad", element: "Ice", role: "Attack", baseAtk: 844, baseCritRate: 5, baseCritDmg: 50 },
  { id: "1301", name: "Brujas", element: "Fire", role: "Attack", baseAtk: 855, baseCritRate: 5, baseCritDmg: 50 },
  { id: "1311", name: "Astra", element: "Ether", role: "Support", baseAtk: 641, baseCritRate: 5, baseCritDmg: 50 },
  { id: "1321", name: "Evelyn", element: "Fire", role: "Attack", baseAtk: 855, baseCritRate: 5, baseCritDmg: 50 },
  { id: "1331", name: "Vivian", element: "Ether", role: "Anomaly", baseAtk: 806, baseCritRate: 5, baseCritDmg: 50 },
  { id: "1341", name: "Xiao Zhao", element: "Ice", role: "Defense", baseAtk: 691, baseCritRate: 5, baseCritDmg: 50 },
  { id: "1351", name: "Pulchra", element: "Physics", role: "Stun", baseAtk: 591, baseCritRate: 5, baseCritDmg: 50 },
  { id: "1361", name: "Trigger", element: "Elec", role: "Stun", baseAtk: 676, baseCritRate: 5, baseCritDmg: 50 },
  { id: "1371", name: "Yi Xuan", element: "AuricEther", role: "Rupture", baseAtk: 873, baseCritRate: 5, baseCritDmg: 50 },
  { id: "1381", name: "Silver Anby", element: "Elec", role: "Attack", baseAtk: 855, baseCritRate: 5, baseCritDmg: 50 },
  { id: "1391", name: "Jufufu", element: "Fire", role: "Stun", baseAtk: 691, baseCritRate: 5, baseCritDmg: 50 },
  { id: "1401", name: "Alice", element: "Physics", role: "Anomaly", baseAtk: 806, baseCritRate: 5, baseCritDmg: 50 },
  { id: "1411", name: "Yuzuha", element: "Physics", role: "Support", baseAtk: 683, baseCritRate: 5, baseCritDmg: 50 },
  { id: "1421", name: "Pan Yinhu", element: "Physics", role: "Defense", baseAtk: 587, baseCritRate: 5, baseCritDmg: 50 },
  { id: "1431", name: "Zhenzhen", element: "ZhenZhenAssault", role: "Attack", baseAtk: 863, baseCritRate: 5, baseCritDmg: 50 },
  { id: "1441", name: "Norano", element: "Fire", role: "Rupture", baseAtk: 680, baseCritRate: 5, baseCritDmg: 50 },
  { id: "1451", name: "Lucia", element: "Ether", role: "Support", baseAtk: 683, baseCritRate: 5, baseCritDmg: 50 },
  { id: "1461", name: "Seed", element: "Elec", role: "Attack", baseAtk: 855, baseCritRate: 5, baseCritDmg: 50 },
  { id: "1471", name: "Ban Yue", element: "Fire", role: "Rupture", baseAtk: 785, baseCritRate: 5, baseCritDmg: 50 },
  { id: "1481", name: "Azural", element: "Physics", role: "Stun", baseAtk: 683, baseCritRate: 5, baseCritDmg: 50 },
  { id: "1491", name: "Summer", element: "Physics", role: "Support", baseAtk: 676, baseCritRate: 5, baseCritDmg: 50 },
  { id: "1501", name: "Aria", element: "Ether", role: "Anomaly", baseAtk: 788, baseCritRate: 5, baseCritDmg: 50 },
  { id: "1511", name: "Nangong Yu", element: "Ether", role: "Stun", baseAtk: 672, baseCritRate: 5, baseCritDmg: 50 },
  { id: "1521", name: "Cissia", element: "Elec", role: "Attack", baseAtk: 863, baseCritRate: 5, baseCritDmg: 50 },
  { id: "1531", name: "SPBilly", element: "Physics", role: "Rupture", baseAtk: 785, baseCritRate: 5, baseCritDmg: 50 },
  { id: "1541", name: "Promeia", element: "Ice", role: "Anomaly", baseAtk: 798, baseCritRate: 5, baseCritDmg: 50 },
  { id: "1551", name: "Pyrois", element: "Ether", role: "Attack", baseAtk: 849, baseCritRate: 5, baseCritDmg: 50 },
  { id: "1561", name: "Velina", element: "Wind", role: "Anomaly", baseAtk: 798, baseCritRate: 5, baseCritDmg: 50 },
  { id: "1571", name: "Norma", element: "Fire", role: "Stun", baseAtk: 687, baseCritRate: 5, baseCritDmg: 50 },
];

