// The ONLY module that loads the WASM solver core. UI/features never import WASM
// directly. See docs/ARCHITECTURE.md (services boundary) and docs/FRONTEND.md.
import { createLogger } from "../lib/logger";

const log = createLogger("wasm-bridge");

export interface SolverApi {
  greet(): string;
  solve(requestJson: string): string;
}

/**
 * Load the compiled WASM core. Until `pnpm build:wasm` has produced it, fall back
 * to a TS stub so the app still runs end to end (the plan's "swappable solver"
 * principle). Once the WASM is built the real core is used transparently.
 */
export async function loadSolver(): Promise<SolverApi> {
  try {
    // Generated by wasm-pack into src/wasm; absent before the first WASM build.
    // Runtime (non-literal) path so `tsc` does not resolve a not-yet-built module.
    const modPath = "../wasm/core_solver.js";
    const wasm = await import(/* @vite-ignore */ modPath);
    await wasm.default();
    log.info("loaded WASM core");
    return { greet: wasm.greet, solve: wasm.solve };
  } catch (err) {
    log.warn("WASM core not built yet — using TS stub", err);
    return {
      greet: () => "core-solver (TS stub) ready",
      solve: () =>
        JSON.stringify({ status: "ok", note: "TS stub: run `pnpm build:wasm` for the real solver" }),
    };
  }
}
